// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items                []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Destination          string   `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_43390cf179a4638a, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "v1.Order")
}

func init() {
	proto.RegisterFile("order-service.proto", fileDescriptor_43390cf179a4638a)
}

var fileDescriptor_43390cf179a4638a = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x45, 0x49, 0xc6, 0x0a, 0x8d, 0x83, 0x8b, 0xe8, 0xa2, 0x14, 0x91, 0xe2, 0xaa, 0x1b, 0x33,
	0x8e, 0xae, 0xfc, 0x0a, 0xa1, 0x03, 0xee, 0x33, 0xc9, 0xb3, 0x3e, 0x18, 0x9b, 0xf0, 0x92, 0xd6,
	0x1f, 0x10, 0xfc, 0x6d, 0x69, 0x32, 0x55, 0x57, 0xb3, 0xbc, 0x27, 0xf7, 0x84, 0x77, 0xc5, 0x95,
	0x23, 0x0b, 0x74, 0x1f, 0x80, 0x26, 0x34, 0xa0, 0x3c, 0xb9, 0xe8, 0x24, 0x9f, 0xb6, 0xf5, 0x6d,
	0xef, 0x5c, 0x7f, 0x80, 0x4d, 0x22, 0xfb, 0xf1, 0x6d, 0xf3, 0x49, 0xda, 0x7b, 0xa0, 0x90, 0x3b,
	0x77, 0xdf, 0x4c, 0x14, 0x2f, 0xb3, 0x2b, 0x2f, 0x05, 0x47, 0x5b, 0xb1, 0x86, 0xb5, 0x65, 0xc7,
	0xd1, 0xca, 0x6b, 0x51, 0x60, 0x84, 0x8f, 0x50, 0xf1, 0x66, 0xd5, 0x96, 0x5d, 0x0e, 0xb2, 0x11,
	0x17, 0x16, 0x82, 0x21, 0xf4, 0x11, 0xdd, 0x50, 0xad, 0x52, 0xfd, 0x3f, 0x9a, 0x3d, 0x4f, 0x68,
	0xa0, 0x3a, 0x6b, 0x58, 0xcb, 0xbb, 0x1c, 0x8e, 0x5e, 0xc4, 0x41, 0x27, 0xaf, 0xf8, 0xf5, 0x16,
	0xf4, 0xf8, 0xc5, 0xc4, 0x3a, 0x5d, 0xb2, 0xcb, 0x23, 0xe4, 0xb3, 0x58, 0x07, 0xd0, 0x64, 0xde,
	0x13, 0x0d, 0xf2, 0x46, 0xe5, 0x2d, 0x6a, 0xd9, 0xa2, 0x76, 0x91, 0x70, 0xe8, 0x5f, 0xf5, 0x61,
	0x84, 0xba, 0x54, 0xd3, 0x56, 0xa5, 0xe6, 0x03, 0x9b, 0xd5, 0xd1, 0x5b, 0x1d, 0xe1, 0xa8, 0xfe,
	0x3d, 0xd6, 0x27, 0x7f, 0x69, 0xd9, 0xfe, 0x3c, 0xf1, 0xa7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x75, 0xc3, 0x8b, 0xb6, 0x52, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	SearchOrders(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (OrderService_SearchOrdersClient, error)
	UpdateOrders(ctx context.Context, opts ...grpc.CallOption) (OrderService_UpdateOrdersClient, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) SearchOrders(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (OrderService_SearchOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderService_serviceDesc.Streams[0], "/v1.OrderService/searchOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderServiceSearchOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderService_SearchOrdersClient interface {
	Recv() (*Order, error)
	grpc.ClientStream
}

type orderServiceSearchOrdersClient struct {
	grpc.ClientStream
}

func (x *orderServiceSearchOrdersClient) Recv() (*Order, error) {
	m := new(Order)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderServiceClient) UpdateOrders(ctx context.Context, opts ...grpc.CallOption) (OrderService_UpdateOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderService_serviceDesc.Streams[1], "/v1.OrderService/updateOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderServiceUpdateOrdersClient{stream}
	return x, nil
}

type OrderService_UpdateOrdersClient interface {
	Send(*Order) error
	CloseAndRecv() (*wrappers.StringValue, error)
	grpc.ClientStream
}

type orderServiceUpdateOrdersClient struct {
	grpc.ClientStream
}

func (x *orderServiceUpdateOrdersClient) Send(m *Order) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderServiceUpdateOrdersClient) CloseAndRecv() (*wrappers.StringValue, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(wrappers.StringValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	SearchOrders(*wrappers.StringValue, OrderService_SearchOrdersServer) error
	UpdateOrders(OrderService_UpdateOrdersServer) error
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) SearchOrders(req *wrappers.StringValue, srv OrderService_SearchOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchOrders not implemented")
}
func (*UnimplementedOrderServiceServer) UpdateOrders(srv OrderService_UpdateOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateOrders not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_SearchOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(wrappers.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderServiceServer).SearchOrders(m, &orderServiceSearchOrdersServer{stream})
}

type OrderService_SearchOrdersServer interface {
	Send(*Order) error
	grpc.ServerStream
}

type orderServiceSearchOrdersServer struct {
	grpc.ServerStream
}

func (x *orderServiceSearchOrdersServer) Send(m *Order) error {
	return x.ServerStream.SendMsg(m)
}

func _OrderService_UpdateOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServiceServer).UpdateOrders(&orderServiceUpdateOrdersServer{stream})
}

type OrderService_UpdateOrdersServer interface {
	SendAndClose(*wrappers.StringValue) error
	Recv() (*Order, error)
	grpc.ServerStream
}

type orderServiceUpdateOrdersServer struct {
	grpc.ServerStream
}

func (x *orderServiceUpdateOrdersServer) SendAndClose(m *wrappers.StringValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderServiceUpdateOrdersServer) Recv() (*Order, error) {
	m := new(Order)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "searchOrders",
			Handler:       _OrderService_SearchOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "updateOrders",
			Handler:       _OrderService_UpdateOrders_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "order-service.proto",
}
